#include <iostream>
#include <cstdlib>
#include <string>
#include <limits>
#include <vector>
#include <algorithm>
#include <sstream>
#include <numeric>
#include <ctime>
#include <cmath>
#include <fstream>
#include <deque>
#include <iterator>
#include <memory>
#include <stdio.h> 
#include <thread>
#include <chrono>
#include <mutex>
using namespace std;