all: BSTtest.cpp BSTtest2.cpp BSTtestCD.cpp BSTtestCL.cpp BSTtestDD.cpp BinarySearchTreeDL.h BinarySearchTreeDD.h BinarySearchTreeCL.h BinarySearchTreeCD.h
	g++ -o BSTtest BSTtest.cpp
	g++ -o BSTtest2 BSTtest2.cpp
	g++ -o BSTtestCD BSTtestCD.cpp
	g++ -o BSTtestCL BSTtestCL.cpp
	g++ -o BSTtestDD BSTtestDD.cpp

clean:
	rm -f BSTtest 
	rm -f BSTtest2 
	rm -f BSTtestCD 
	rm -f BSTtestCL 
	rm -f BSTtestDD

run:
	./BSTtest
	./BSTtest2
	./BSTtestCD
	./BSTtestCL
	./BSTtestDD